# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\des.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""интерфейс главного окна"""
from PyQt5 import QtCore, QtGui, QtWidgets
from locale import getlocale
"""В этом файле прописан только интерфейс, вся логика находится в main.py"""


class Ui_MainWindow(object):
    """функция обьявления всех обьектов в интерфейсе главного окна"""

    def setupUi(self, MainWindow):
        """обьявление главного окна и его характеристик"""
        MainWindow.setObjectName("MainWindow")
        """размеры окна"""
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        """шрифт окна и статус бара (т.к. шрифт не указан, по умолчанию ставится MS Shell Dog)"""
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        """создание виджета окна"""
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        """horizontalLayoutWidget - виджет, созданный для баланса в расстоянии между обьектами по горизонтали"""
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 539, 781, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_redact = QtWidgets.QPushButton(
            self.horizontalLayoutWidget)
        """Кнопка для редактирования задачи (функционал не реализован)"""
        self.pushButton_redact.setObjectName("pushButton_redact")
        """Добавление кнопки в horizontalLayoutWidget"""
        self.horizontalLayout.addWidget(self.pushButton_redact)
        """spacer - виджет для обеспечения расстояния между виджетами"""
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        """кнопка для удаления задачи"""
        self.pushButton_delete = QtWidgets.QPushButton(
            self.horizontalLayoutWidget)
        self.pushButton_delete.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout.addWidget(self.pushButton_delete)
        """listWidget - виджет для отображения списка задач и взаимодействия с ними"""
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 261, 491))
        self.listWidget.setObjectName("listWidget")
        """textBrowser - виджет для вывода текста, в данном случае для подробного описания задачи(не реализовано)"""
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(280, 40, 511, 271))
        self.textBrowser.setObjectName("textBrowser")
        """label - строчка с коротким текстом, в данном контексте используется просто как указатель что есть что"""
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(16, 10, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 10, 511, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        """calendarWidget - виджет календаря"""
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(280, 320, 511, 211))
        self.calendarWidget.setObjectName("calendarWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        """обьявление menubar и его инструментов"""
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.create_task = QtWidgets.QAction(MainWindow)
        self.create_task.setObjectName("create_task")
        self.stand_time = QtWidgets.QAction(MainWindow)
        self.stand_time.setObjectName("stand_time")
        self.pomidor = QtWidgets.QAction(MainWindow)
        self.pomidor.setObjectName("pomidor")
        self.refresh = QtWidgets.QAction(MainWindow)
        self.refresh.setObjectName("refresh")
        self.menu.addAction(self.create_task)
        self.menu.addAction(self.refresh)
        self.menu_2.addAction(self.stand_time)
        self.menu_2.addAction(self.pomidor)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        if getlocale()[0] == "Russian_Russia":
            """функция присваивания определенного текста  определенному элемента интерфейса"""
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate(
                "MainWindow", "Планировщик задач"))
            self.pushButton_redact.setText(
                _translate("MainWindow", "Редактировать"))
            self.pushButton_delete.setText(_translate("MainWindow", "Удалить"))
            self.label.setText(_translate("MainWindow", "Задачи"))
            self.label_2.setText(_translate("MainWindow", "Описание"))
            self.menu.setTitle(_translate("MainWindow", "Задача"))
            self.menu_2.setTitle(_translate("MainWindow", "Таймер"))
            self.create_task.setText(_translate(
                "MainWindow", "Создать задачу"))
            self.stand_time.setText(_translate(
                "MainWindow", "Стандартный таймер"))
            self.pomidor.setText(_translate(
                "MainWindow", "Таймер \"Помидор\""))
            self.refresh.setText(_translate(
                "MainWindow", "Обновить список (F5)"))
        else:
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate(
                "MainWindow", "Task manager"))
            self.pushButton_redact.setText(
                _translate("MainWindow", "Edit"))
            self.pushButton_delete.setText(_translate("MainWindow", "Delete"))
            self.label.setText(_translate("MainWindow", "Tasks"))
            self.label_2.setText(_translate("MainWindow", "Description"))
            self.menu.setTitle(_translate("MainWindow", "Task"))
            self.menu_2.setTitle(_translate("MainWindow", "Timer"))
            self.create_task.setText(_translate(
                "MainWindow", "Create task"))
            self.stand_time.setText(_translate(
                "MainWindow", "Default timer"))
            self.pomidor.setText(_translate(
                "MainWindow", "Pomodoro timer"))
            self.refresh.setText(_translate(
                "MainWindow", "Refresh (F5)"))
