# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pomidor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_pomidor(object):
    def setupUi(self, form_pomidor):
        form_pomidor.setObjectName("form_pomidor")
        form_pomidor.resize(480, 640)
        form_pomidor.setMinimumSize(QtCore.QSize(480, 640))
        form_pomidor.setMaximumSize(QtCore.QSize(480, 640))
        self.label = QtWidgets.QLabel(form_pomidor)
        self.label.setGeometry(QtCore.QRect(250, 240, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(form_pomidor)
        self.spinBox.setGeometry(QtCore.QRect(100, 240, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.spinBox.setFont(font)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(5)
        self.spinBox.setObjectName("spinBox")
        self.start_button = QtWidgets.QPushButton(form_pomidor)
        self.start_button.setGeometry(QtCore.QRect(-10, 520, 500, 130))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.stop_button = QtWidgets.QPushButton(form_pomidor)
        self.stop_button.setGeometry(QtCore.QRect(-10, 517, 500, 130))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.stop_button.setFont(font)
        self.stop_button.setObjectName("stop_button")
        self.lcdrabota = QtWidgets.QLCDNumber(form_pomidor)
        self.lcdrabota.setGeometry(QtCore.QRect(0, 160, 481, 141))
        self.lcdrabota.setObjectName("lcdrabota")
        self.lcdotdih = QtWidgets.QLCDNumber(form_pomidor)
        self.lcdotdih.setGeometry(QtCore.QRect(-10, 160, 501, 141))
        self.lcdotdih.setObjectName("lcdotdih")
        self.label_rabota = QtWidgets.QLabel(form_pomidor)
        self.label_rabota.setGeometry(QtCore.QRect(-10, 330, 480, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_rabota.setFont(font)
        self.label_rabota.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rabota.setObjectName("label_rabota")
        self.label_otdih = QtWidgets.QLabel(form_pomidor)
        self.label_otdih.setGeometry(QtCore.QRect(0, 330, 480, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_otdih.setFont(font)
        self.label_otdih.setAlignment(QtCore.Qt.AlignCenter)
        self.label_otdih.setObjectName("label_otdih")
        self.label_podhod = QtWidgets.QLabel(form_pomidor)
        self.label_podhod.setGeometry(QtCore.QRect(-6, 100, 491, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_podhod.setFont(font)
        self.label_podhod.setAlignment(QtCore.Qt.AlignCenter)
        self.label_podhod.setObjectName("label_podhod")

        self.retranslateUi(form_pomidor)
        QtCore.QMetaObject.connectSlotsByName(form_pomidor)

    def retranslateUi(self, form_pomidor):
        _translate = QtCore.QCoreApplication.translate
        form_pomidor.setWindowTitle(_translate("form_pomidor", "Form"))
        self.label.setText(_translate("form_pomidor", "\"помидоров\""))
        self.start_button.setText(_translate("form_pomidor", "Старт"))
        self.stop_button.setText(_translate("form_pomidor", "Стоп"))
        self.label_rabota.setText(_translate("form_pomidor", "Работа"))
        self.label_otdih.setText(_translate("form_pomidor", "Отдых"))
        self.label_podhod.setText(_translate("form_pomidor", "TextLabel"))
