# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\task_wid.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_task(object):
    def setupUi(self, Form_task):
        Form_task.setObjectName("Form_task")
        Form_task.resize(480, 640)
        Form_task.setMinimumSize(QtCore.QSize(480, 640))
        Form_task.setMaximumSize(QtCore.QSize(480, 640))
        self.label_task = QtWidgets.QLabel(Form_task)
        self.label_task.setGeometry(QtCore.QRect(10, 51, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_task.setFont(font)
        self.label_task.setObjectName("label_task")
        self.lineEdit_task = QtWidgets.QLineEdit(Form_task)
        self.lineEdit_task.setGeometry(QtCore.QRect(180, 50, 291, 20))
        self.lineEdit_task.setMaxLength(32)
        self.lineEdit_task.setObjectName("lineEdit_task")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form_task)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 160, 461, 221))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_description = QtWidgets.QLabel(Form_task)
        self.label_description.setGeometry(QtCore.QRect(10, 135, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_description.setFont(font)
        self.label_description.setObjectName("label_description")
        self.timeEdit = QtWidgets.QTimeEdit(Form_task)
        self.timeEdit.setGeometry(QtCore.QRect(10, 410, 121, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.label_time = QtWidgets.QLabel(Form_task)
        self.label_time.setGeometry(QtCore.QRect(140, 410, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.checkBox_time = QtWidgets.QCheckBox(Form_task)
        self.checkBox_time.setGeometry(QtCore.QRect(10, 440, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_time.setFont(font)
        self.checkBox_time.setObjectName("checkBox_time")
        self.dateEdit = QtWidgets.QDateEdit(Form_task)
        self.dateEdit.setGeometry(QtCore.QRect(10, 468, 121, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.checkBox_date = QtWidgets.QCheckBox(Form_task)
        self.checkBox_date.setGeometry(QtCore.QRect(10, 498, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_date.setFont(font)
        self.checkBox_date.setObjectName("checkBox_date")
        self.label_date = QtWidgets.QLabel(Form_task)
        self.label_date.setGeometry(QtCore.QRect(140, 470, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_date.setFont(font)
        self.label_date.setObjectName("label_date")
        self.pushButton_create = QtWidgets.QPushButton(Form_task)
        self.pushButton_create.setGeometry(QtCore.QRect(-2, 541, 484, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_create.setFont(font)
        self.pushButton_create.setObjectName("pushButton_create")

        self.retranslateUi(Form_task)
        QtCore.QMetaObject.connectSlotsByName(Form_task)

    def retranslateUi(self, Form_task):
        _translate = QtCore.QCoreApplication.translate
        Form_task.setWindowTitle(_translate("Form_task", "Form"))
        self.label_task.setText(_translate("Form_task", "Название задачи:"))
        self.label_description.setText(_translate("Form_task", "Описание задачи:"))
        self.label_time.setText(_translate("Form_task", "Время задачи"))
        self.checkBox_time.setText(_translate("Form_task", "Без определенного времени"))
        self.checkBox_date.setText(_translate("Form_task", "Без определенной даты"))
        self.label_date.setText(_translate("Form_task", "Дата задачи"))
        self.pushButton_create.setText(_translate("Form_task", "Создать задачу"))
